receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4817
      http:
        endpoint: 0.0.0.0:4818

processors:
  batch:

exporters:
  otlp/jaeger:
    endpoint: "jaeger:4317"
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/jaeger]