// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.11
// source: english.proto

package english

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	English_Ping_FullMethodName = "/english.English/Ping"
)

// EnglishClient is the client API for English service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EnglishClient interface {
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type englishClient struct {
	cc grpc.ClientConnInterface
}

func NewEnglishClient(cc grpc.ClientConnInterface) EnglishClient {
	return &englishClient{cc}
}

func (c *englishClient) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, English_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EnglishServer is the server API for English service.
// All implementations must embed UnimplementedEnglishServer
// for forward compatibility.
type EnglishServer interface {
	Ping(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedEnglishServer()
}

// UnimplementedEnglishServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEnglishServer struct{}

func (UnimplementedEnglishServer) Ping(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedEnglishServer) mustEmbedUnimplementedEnglishServer() {}
func (UnimplementedEnglishServer) testEmbeddedByValue()                 {}

// UnsafeEnglishServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EnglishServer will
// result in compilation errors.
type UnsafeEnglishServer interface {
	mustEmbedUnimplementedEnglishServer()
}

func RegisterEnglishServer(s grpc.ServiceRegistrar, srv EnglishServer) {
	// If the following call pancis, it indicates UnimplementedEnglishServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&English_ServiceDesc, srv)
}

func _English_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnglishServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: English_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnglishServer).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// English_ServiceDesc is the grpc.ServiceDesc for English service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var English_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "english.English",
	HandlerType: (*EnglishServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _English_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "english.proto",
}
