// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1
// Source: chinese.proto

package chineseclient

import (
	"context"

	"hello/chinese/chinese"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = chinese.Request
	Response = chinese.Response

	Chinese interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultChinese struct {
		cli zrpc.Client
	}
)

func NewChinese(cli zrpc.Client) Chinese {
	return &defaultChinese{
		cli: cli,
	}
}

func (m *defaultChinese) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := chinese.NewChineseClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
