// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.11
// source: chinese.proto

package chinese

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Chinese_Ping_FullMethodName = "/chinese.Chinese/Ping"
)

// ChineseClient is the client API for Chinese service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChineseClient interface {
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type chineseClient struct {
	cc grpc.ClientConnInterface
}

func NewChineseClient(cc grpc.ClientConnInterface) ChineseClient {
	return &chineseClient{cc}
}

func (c *chineseClient) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, Chinese_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChineseServer is the server API for Chinese service.
// All implementations must embed UnimplementedChineseServer
// for forward compatibility.
type ChineseServer interface {
	Ping(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedChineseServer()
}

// UnimplementedChineseServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChineseServer struct{}

func (UnimplementedChineseServer) Ping(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedChineseServer) mustEmbedUnimplementedChineseServer() {}
func (UnimplementedChineseServer) testEmbeddedByValue()                 {}

// UnsafeChineseServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChineseServer will
// result in compilation errors.
type UnsafeChineseServer interface {
	mustEmbedUnimplementedChineseServer()
}

func RegisterChineseServer(s grpc.ServiceRegistrar, srv ChineseServer) {
	// If the following call pancis, it indicates UnimplementedChineseServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Chinese_ServiceDesc, srv)
}

func _Chinese_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChineseServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chinese_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChineseServer).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Chinese_ServiceDesc is the grpc.ServiceDesc for Chinese service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Chinese_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chinese.Chinese",
	HandlerType: (*ChineseServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Chinese_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chinese.proto",
}
