// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1
// Source: chinese.proto

package server

import (
	"context"

	"hello/chinese/chinese"
	"hello/chinese/internal/logic"
	"hello/chinese/internal/svc"
)

type ChineseServer struct {
	svcCtx *svc.ServiceContext
	chinese.UnimplementedChineseServer
}

func NewChineseServer(svcCtx *svc.ServiceContext) *ChineseServer {
	return &ChineseServer{
		svcCtx: svcCtx,
	}
}

func (s *ChineseServer) Ping(ctx context.Context, in *chinese.Request) (*chinese.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
