// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1
// Source: english.proto

package server

import (
	"context"

	"hello/english/english"
	"hello/english/internal/logic"
	"hello/english/internal/svc"
)

type EnglishServer struct {
	svcCtx *svc.ServiceContext
	english.UnimplementedEnglishServer
}

func NewEnglishServer(svcCtx *svc.ServiceContext) *EnglishServer {
	return &EnglishServer{
		svcCtx: svcCtx,
	}
}

func (s *EnglishServer) Ping(ctx context.Context, in *english.Request) (*english.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
